name: BMW Premium Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout BMW Browser
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Configure signing
        run: echo "autosignReleaseWithDebugKey=" >> local.properties

      - name: Build BMW Browser
        run: ./gradlew app:assemblefenixForkRelease -PversionName="1.0.0"

      - name: Upload BMW APK
        uses: actions/upload-artifact@v4
        with:
          name: BMW-Browser-APK
          path: app/build/outputs/apk/fenix/forkRelease/*.apk
          if-no-files-found: error
